FROM rust:latest as builder
WORKDIR /usr/src/server
COPY . .
RUN cargo install --path ./server
RUN cargo install diesel_cli --no-default-features --features postgres

FROM debian:buster-slim
RUN apt-get update && apt-get install postgresql -y
COPY ./wait-for-it.sh ./wait-for-it.sh
COPY --from=builder /usr/local/cargo/bin/diesel /usr/local/bin/diesel
COPY ./server/kotc_database/migrations ./migrations
COPY --from=builder /usr/local/cargo/bin/server /usr/local/bin/server
CMD ["server"]
