version: '3.3'
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    ports:
      - "8080:8080"
    environment:
      SERVER_URL: 127.0.0.1:8081
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:password@db/kotc
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432"]

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kotc
