name: Build and Publish Docker images

on:
  push:
    branches: [master]

jobs:
  build-and-push-docker-server:
    name: Docker image server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build server image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.server
          tags: |
            puckoland/king-of-the-castle-server:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-and-push-docker-client:
    name: Docker image client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build client image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.client
          tags: |
            puckoland/king-of-the-castle-client:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
